


CREATE DATABASE IF NOT EXISTS lakobra;
USE lakobra;

-- Tabla SOCIOS --
CREATE TABLE SOCIOS(
    NUM_SOCIO INT PRIMARY KEY,
    DNI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    CHECK (dni REGEXP '^[0-9]{8}[A-Za-z]$'),
    CHECK (email LIKE '%@%')
);

-- Tabla EVENTOS --
CREATE TABLE EVENTOS(
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOM_EVENTO VARCHAR(50) NOT NULL,
    DESC_EVENTO VARCHAR(100) NOT NULL,
    ARTISTA VARCHAR(50),
    FECHA DATE,
    TIPO VARCHAR(30)
);

-- Tabla TXANDALARIS
CREATE TABLE TXANDALARIS(
    ID_TXANDALARI INT AUTO_INCREMENT PRIMARY KEY,
    NUM_SOCIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    ACTIVIDAD VARCHAR(30),
    CONSTRAINT fk_NUM_SOCIO FOREIGN KEY(NUM_SOCIO) REFERENCES SOCIOS(NUM_SOCIO),
    CONSTRAINT fk_ID_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
    CONSTRAINT unique_txandalaris UNIQUE(NUM_SOCIO, ID_EVENTO)
);

-- Tabla INSCRIPCIONES
CREATE TABLE INSCRIPCIONES(
    ID_INSCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
    NUM_SOCIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    FECHA_INSCRIPCION DATE,
    ESTADO VARCHAR(20),
    FOREIGN KEY(NUM_SOCIO) REFERENCES SOCIOS(NUM_SOCIO),
    FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO),
    CONSTRAINT unique_inscripcion UNIQUE(NUM_SOCIO, ID_EVENTO)
);

-- Tabla ARTISTAS
CREATE TABLE ARTISTAS(
    ID_ARTISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    GENERO VARCHAR(30),
    PAIS VARCHAR(50)
);

-- Trigger para INSCRIPCIONES
DELIMITER $$
CREATE TRIGGER evitar_repetido_inscripcion
BEFORE INSERT ON INSCRIPCIONES
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM INSCRIPCIONES
        WHERE NUM_SOCIO = NEW.NUM_SOCIO
          AND ID_EVENTO = NEW.ID_EVENTO
    ) THEN
        SIGNAL SQLSTATE '23000'
        SET MESSAGE_TEXT = 'Este socio ya está inscrito en este evento';
    END IF;
END$$
DELIMITER ;

-- Trigger para TXANDALARIS (evitar duplicados)
DELIMITER $$
CREATE TRIGGER evitar_repetido_txandalaris
BEFORE INSERT ON TXANDALARIS
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM TXANDALARIS
        WHERE NUM_SOCIO = NEW.NUM_SOCIO
          AND ID_EVENTO = NEW.ID_EVENTO
    ) THEN
        SIGNAL SQLSTATE '23000'
        SET MESSAGE_TEXT = 'Este socio ya participa en este evento como txandalari';
    END IF;
END$$
DELIMITER ;